services:
  - type: web
    name: BotAiVids
    env: python
    plan: free
    branch: main
    region: oregon
    buildCommand: |
      pip install -r requirements.txt
    startCommand: gunicorn main:app --bind 0.0.0.0:$PORT
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
